import "./globals.css";
import { Inter } from "next/font/google";
import LocalMediaProvider from "@/contexts/LocalMediaContext";
import StageProvider from "@/contexts/StageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalMediaProvider>
          <StageProvider>{children}</StageProvider>
        </LocalMediaProvider>
      </body>
    </html>
  );
}
